package fluentd

import (
	"fmt"
	"strings"
)

var defaultLokiLabelKeys = []string{
	"log_type",
	"kubernetes.namespace_name",
	"kubernetes.pod_name",
	"kubernetes.host",
}

func (conf *outputLabelConf) lokiLabelKeys() []string {
	labelKeys := defaultLokiLabelKeys
	if conf.Target.Loki != nil && len(conf.Target.Loki.LabelKeys) != 0 {
		labelKeys = conf.Target.Loki.LabelKeys
	}
	//  Make sure host is always included
	for _, k := range labelKeys {
		if k == "kubernetes.host" {
			return labelKeys
		}
	}
	return append(labelKeys, "kubernetes.host")
}

// LokiLabelFilter generates record_modifier filter lines to copy Loki label fields.
// The Loki output plugin will remove these fields after creating Loki labels.
func (conf *outputLabelConf) LokiLabelFilter() string {
	b := &strings.Builder{}
	for _, k := range conf.lokiLabelKeys() {
		tempName := strings.Replace(k, ".", "_", -1)
		recordKeys := strings.Replace(k, ".", `","`, -1)
		fmt.Fprintf(b, "\n    _%v ${record.dig(\"%v\")}", tempName, recordKeys)
	}
	return b.String()
}

// LokiLabel generates the <label> entries for Loki output config.
// This consumes the fields generated by LokiLabelFilter.
func (conf *outputLabelConf) LokiLabel() string {
	b := &strings.Builder{}
	for _, k := range conf.lokiLabelKeys() {
		tempName := strings.Replace(k, ".", "_", -1)
		fmt.Fprintf(b, "\n      %v _%v", tempName, tempName)
	}
	return b.String()
}
