name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Checkout
      uses: actions/checkout@v2

    - name: Check
      run: |
        make test-unit bin/forwarder-generator bin/cluster-logging-operator
	      go test ./test/... -exec true > /dev/null # Build but don't run e2e tests.

